### PR TITLE
[AAP-12376] Check to make sure only one AWX token exists

### PR DESCRIPTION
**Pull request by ddonahue007**
[AAP-12376](https://issues.redhat.com/browse/AAP-12376) 

Only grab the first token. So checking to make sure we have at least one token makes sense.

### CODE REVIEW

**Comment by benthomasson** [comment]
We also wait and implement support for multiple tokens and avoid this problem together.

**Comment by Alex-Izquierdo** [comment]
I swear I didn't closed this PR, must be an accident. It can not be reopened, I guess because the fork is private (it returns 404). I'm trying to speak with @ddonahue007 to unblock it.

**Comment by ddonahue007** [comment]
> 

I opened the repo to be public. I am not able to re-open this PR, maybe I do not have the rights in the project any longer?

**Comment by Alex-Izquierdo** [comment]
Reopened. Thanks @ddonahue007

**Comment by Alex-Izquierdo** [comment]
It's very weird, every time I open it its closed automatically.

**Pull request closed without merging**
