### PR TITLE
Add eda to the service mesh network

### PR DESCRIPTION
**Pull request by chrismeyersfsu**
* Join a common named network that components can discover one another and talk on. Related to https://github.com/ansible/aap-gateway/pull/235

### CODE REVIEW

**Review by Alex-Izquierdo — CHANGES_REQUESTED** [review]
```
ERROR: In file '././tools/docker/docker-compose-dev.yaml', networks must be a mapping, not an array.

```

**Comment by chrismeyersfsu** [comment]
wow, that makes me look like a n00b that didn't even run this, but I promise it was a copy paste error .. fixing. Thanks for looking!

**Comment by chrismeyersfsu** [comment]
> ```
> ERROR: In file '././tools/docker/docker-compose-dev.yaml', networks must be a mapping, not an array.
> ```

addressed (Trying to figure out how to resolve the github requested changes blocker. I believe I've addressed the spirit of the request and it is now the tooling that is blocking me).

image

**Comment by Dostonbek1** [comment]
> > ```
> > ERROR: In file '././tools/docker/docker-compose-dev.yaml', networks must be a mapping, not an array.
> > ```
> 
> addressed (Trying to figure out how to resolve the github requested changes blocker. I believe I've addressed the spirit of the request and it is now the tooling that is blocking me).
> 
> image

Once @Alex-Izquierdo approves, the blocker will go away, also this repo needs 2 approvals to merge a PR.

**Review by Alex-Izquierdo — APPROVED** [review]

**Pull request merged**
