### PR TITLE
Update DAB to tag 2024.6.11

### PR DESCRIPTION
**Pull request by bzwei**

### CODE REVIEW

**Comment by bzwei** [comment]
cc @AlanCoding

**Comment by AlanCoding** [comment]
Thanks, only concern is if we need https://github.com/ansible/django-ansible-base/pull/420 which didn't make that tag. Let me get back to you in 1 hour about that ping @john-westcott-iv

**Comment by mkanoor** [comment]
@bzwei Lets wait for PR https://github.com/ansible/django-ansible-base/pull/420

**Comment by bzwei** [comment]
updated to latest tag 2024.6.11 commit c5e7ac8

**Review by mkanoor — APPROVED** [review]

**Review by hsong-rh — APPROVED** [review]

**Pull request merged**
