### PR TITLE
Set current_job_id for activations started by scheduler

### PR DESCRIPTION
**Pull request by bzwei**
Minor fix. Self explained.

### CODE REVIEW

**Comment by hsong-rh** [comment]
@bzwei https://github.com/ansible/eda-server/blob/main/src/aap_eda/tasks/ruleset.py#L158 needs the similar fix, can you do it together?

**Review by hsong-rh — APPROVED** [review]

**Comment by Alex-Izquierdo** [comment]
Shouldn't we do the same when we call `deactivate.delay`?

**Comment by hsong-rh** [comment]
> Shouldn't we do the same when we call `deactivate.delay`?

@Alex-Izquierdo https://github.com/ansible/eda-server/blob/main/src/aap_eda/tasks/ruleset.py#L114 set it to None already

**Comment by hsong-rh** [comment]
@bzwei should we move the saving current_job_id logic inside `activate`, so no need to call it from outside multiple times? Something like:
```
def activate(activation_id: int, requester: str = "User") -> None:
....
    job = get_current_job()
    activation.current_job_id = job.id
    activation.save(update_fields=["current_job_id"])
....
```

**Comment by bzwei** [comment]
> @bzwei should we move the saving current_job_id logic inside `activate`, so no need to call it from outside multiple times? Something like:
> 
> ```
> def activate(activation_id: int, requester: str = "User") -> None:
> ....
>     job = get_current_job()
>     activation.current_job_id = job.id
>     activation.save(update_fields=["current_job_id"])
> ....
> ```

Unfortunately we can't do this. We need to save the job id as soon as it is queued, but not when it is executed.

**Review by Alex-Izquierdo — APPROVED** [review]

**Pull request merged**
