### PR TITLE
Allow references is nullable in the output of eda credential

### PR DESCRIPTION
**Pull request by hsong-rh**
https://issues.redhat.com/browse/AAP-22188

### CODE REVIEW

**Review by Alex-Izquierdo — APPROVED** [review]

**Review by mkanoor — APPROVED** [review]

**Comment by hsong-rh** [comment]
@Alex-Izquierdo @ttuffin CI failed with:
```
  /usr/bin/docker pull quay.io/sclorg/redis-6-c9s:latest
  Error response from daemon: unknown: Tag latest was deleted or has expired. To pull, revive via time machine
  Error: Docker pull failed with exit code 1
```
Do you have clues about it?

**Comment by Alex-Izquierdo** [comment]
there is no "latest" tag in the image, it can be an issue or they have remove it on purpose.

**Comment by Alex-Izquierdo** [comment]
```
This image is no longer being rebuilt. The latest tag was removed. Please consider using a supported image.
```

From https://quay.io/repository/sclorg/redis-6-c9s?tab=info

**Comment by Alex-Izquierdo** [comment]
https://github.com/ansible/eda-server/pull/789

**Pull request merged**
