### PR TITLE
feat: Add CRUD log messages

### PR DESCRIPTION
**Pull request by zkayyali812**
Description: Adds CRUD logging messages to core EDA resources.
Jira: https://issues.redhat.com/browse/AAP-29258

**Rulebook Activations** Logging added for following operations- 

1. Create
2. Read
3. Update
4. Delete
5. ListActivations
6. Enable
7. Disable
8. Restart

**Decision Environments** Logging  added for following operations- 

1. Create
2. Read
3. Update
4. Delete

**Project** Logging added for following operations-

1. Create
2. Read
3. Update
4. Delete
5. Sync

EventStreams Logging added for following operations -
1. Create
2. Read
3. Update
4. Delete
5. List
6. ListActivations

Rulebook Activation Start/Stop/Restart (Already exists)
1. [Activation Start](https://github.com/ansible/eda-server/blob/main/src/aap_eda/services/activation/activation_manager.py#L651)
    1. Has many [log messsages](https://github.com/ansible/eda-server/blob/main/src/aap_eda/services/activation/activation_manager.py#L179) including various statuses an activation may hit
2. [Activation Stop](https://github.com/ansible/eda-server/blob/main/src/aap_eda/services/activation/activation_manager.py#L687)
3. [Activation Restart](https://github.com/ansible/eda-server/blob/main/src/aap_eda/services/activation/activation_manager.py#L738)
4. [Activation Delete](https://github.com/ansible/eda-server/blob/main/src/aap_eda/services/activation/activation_manager.py#L761-L764)

### CODE REVIEW

**Comment by mkanoor** [comment]
@zkayyali812 Would it be possible to use a separate package like this one https://github.com/jjkester/django-auditlog

**Comment by zkayyali812** [comment]
@mkanoor 
Preferably for event 1, we should keep this change simple to avoid any potential changes to our downstream build.
For this reason, this PR uses just the simple logger.

I expect if we used an alternate library here, there could be potential of downstream impact.
For event 2 the plan is to revisit this to implement a more robust logging/auditing solution.

**Comment by zkayyali812** [comment]
e2e tests now pass without read enabled. Will test again with read enabled.

**Review by dhaustein — APPROVED** [review]

**Review by ttuffin — COMMENTED** [review]
Shall we include the resource ID in the logs as well? It is possible to ascertain the ID from the previous call to the API, as long as the server is not processing parallel requests. For example:
```
eda-api-1                      | 2024-08-15 01:20:22,789 django.channels.server INFO     HTTP GET /api/eda/v1/projects/1/ 200 [0.19, 172.18.0.1:34558]
eda-api-1                      | 2024-08-15 01:20:23,550 aap_eda.api.views.project INFO     Action: Read / ResourceType: Project / ResourceName: QE-project 1YuqSVFtgHfJzROfvtCV4 / Organization: Default
```

But on a busy server that it processing many requests in parallel this will become difficult, e.g:
```
eda-api-1                      | 2024-08-15 01:20:26,326 django.channels.server INFO     HTTP GET /api/eda/v1/activations/1/ 200 [0.31, 172.18.0.1:34558]
eda-api-1                      | 2024-08-15 01:20:26,328 django.channels.server INFO     HTTP GET /api/eda/v1/activations/2/ 200 [0.30, 172.18.0.1:33632]
eda-api-1                      | 2024-08-15 01:20:26,961 aap_eda.api.views.activation INFO     Action: Read / ResourceType: RulebookActivation / ResourceName: QE-activation-batch---1a2AdC34aba3BbaBAb2c4 / Organization: Default
```

Including the ID in the CRUD logs will make it clear.

**Review by ttuffin — APPROVED** [review]

**Review by dhaustein — APPROVED** [review]

**Pull request merged**
