### PR TITLE
fix: remove tracebacks from backend logs when pulling image is timed out

### PR DESCRIPTION
**Pull request by hsong-rh**
https://issues.redhat.com/browse/AAP-20968

### CODE REVIEW

**Comment by mkanoor** [comment]
@hsong-rh Do you have a screen shot of how this would look like in the UI?

**Review by Alex-Izquierdo — COMMENTED** [review]
Have you really tested it in a real environment? I would say the exception is raised by the RQ worker, not by the podman client, so catching the exception inside the code that is executed would not have any effect. I would say the logic to handle JobTimeoutException must be outside the job, at the orchestrator level.

**Comment by hsong-rh** [comment]
@mkanoor With the fix, the UI displays as the screenshot when the job is timed out (Changed timeout to 5 seconds for testing purposes). 
image

**Comment by hsong-rh** [comment]
@Alex-Izquierdo The backend logs are like:
```
docker-eda-activation-worker-2  | 2024-03-05 15:04:08,225 aap_eda.services.activation.engine.podman INFO     Image URL is quay.io/ansible/ansible-rulebook:main
docker-eda-activation-worker-2  | 2024-03-05 15:04:08,240 aap_eda.services.activation.engine.podman INFO     Pulling image : quay.io/ansible/ansible-rulebook:main
docker-eda-activation-worker-2  | 2024-03-05 15:04:12,866 aap_eda.services.activation.engine.podman ERROR    Timeout: Task exceeded maximum timeout value (5 seconds)
docker-eda-activation-worker-2  | 2024-03-05 15:04:12,879 aap_eda.services.activation.manager INFO     Failed policy called for activation id: 1
docker-eda-activation-worker-2  | 2024-03-05 15:04:12,879 aap_eda.services.activation.manager INFO     Activation id: 1 Restart policy is set to never.
docker-eda-activation-worker-2  | 2024-03-05 15:04:12,886 aap_eda.services.activation.manager INFO     Cleanup operation requested for activation id: 1
docker-eda-activation-worker-2  | 2024-03-05 15:04:12,886 aap_eda.services.activation.manager INFO     Cleanup operation activation id: 1 No instance or pod id found.
```
The timeout exception is caught in the real scenario. I think it's better to handle it ASAP.

**Review by Alex-Izquierdo — APPROVED** [review]
I don't understand how it works if the exception is raised by the worker but if it works, LGTM.

**Review by mkanoor — APPROVED** [review]

**Pull request merged**
