### PR TITLE
[UI] [AAP-6018] Part 2 - Replace fetch with axios

### PR DESCRIPTION
**Pull request by lgalis**
- Replace fetch with axios for all endpoints.
- Updated tests to use axios mock

### CODE REVIEW

**Review by ddonahue007 — APPROVED** [review]
lgtm

**Review by eclarizio — CHANGES_REQUESTED** [review]
Now that #227 is merged, rebasing here should make this much easier to review 😄

**Comment by lgalis** [comment]
@eclarizio , @ddonahue007 - rebased

**Review by eclarizio — APPROVED** [review]
LGTM

**Review by ddonahue007 — APPROVED** [review]

**Pull request merged**
