### PR TITLE
Update extravar and playbook urls

### PR DESCRIPTION
**Pull request by lgalis**
Fixed the playbook and extravars get urls

 - Fixes the list of playbook and extravars in the New Activation and New Job forms following the RBAC PR

### CODE REVIEW

**Comment by ttuffin** [comment]
We actually have a bug open (AAP-7409) to remove the trailing slashes on the API side in order to align with the [API design guide](https://github.com/ansible/eda-server/blob/main/README-API.md). So I think this change should not go ahead?

**Comment by Alex-Izquierdo** [comment]
Indeed, if this bug is accepted: https://issues.redhat.com/browse/AAP-7409 (I see no reason not to.) This PR would be unnecessary.

**Comment by lgalis** [comment]
@ttuffin, @Alex-Izquierdo - AAP-7409 was not yet assigned - I have asked in the team chat to see if someone can work on this. If not - we can merge this PR and revert when the API is fixed

**Comment by lgalis** [comment]
Closing as it was fixed on the api side https://github.com/ansible/eda-server/pull/284

**Pull request closed without merging**
