### PR TITLE
AAP-20372 - Merge Bugfix/injectors `Feature` branch into main

### PR DESCRIPTION
**Pull request by zkayyali812**
Brings in the relevant updates from our bugfix/injectors branch into our main to better achieve parity with the platform.

### CODE REVIEW

**Comment by Alex-Izquierdo** [comment]
There is a minor issue with sorted imports, probably caused by my last rebase. 
```
ERROR: /home/runner/work/eda-server/eda-server/src/aap_eda/core/validators.py Imports are incorrectly sorted and/or formatted.
```

Do we want to rebase this PR instead of squash, am I right?

**Comment by zkayyali812** [comment]
@Alex-Izquierdo I think rebasing sounds good, but open to other recommendations. That way we keep the proper commit history.

**Comment by Alex-Izquierdo** [comment]
> @Alex-Izquierdo I think rebasing sounds good, but open to other recommendations. That way we keep the proper commit history.

@mkanoor @Dostonbek1 @bzwei @hsong-rh Is there some commit that should be squashed or as it is now is correct?, maybe the fix ones?

**Comment by Dostonbek1** [comment]
> > @Alex-Izquierdo I think rebasing sounds good, but open to other recommendations. That way we keep the proper commit history.
> 
> @mkanoor @Dostonbek1 @bzwei @hsong-rh Is there some commit that should be squashed or as it is now is correct?, maybe the fix ones?

AFAIK, this looks good as is now. As for "fix" commits, those who worked on them could speak for them.

**Comment by mkanoor** [comment]
Looks good

**Review by hsong-rh — APPROVED** [review]

**Review by Dostonbek1 — APPROVED** [review]

**Review by mkanoor — APPROVED** [review]

**Pull request merged**
