### PR TITLE
fix(AAP-28076): remove org id from credential type

### PR DESCRIPTION
**Pull request by Alex-Izquierdo**
We return an empty list of credential types for every user that doesn't belong to the default organization. 
As we agreed in internal discussions, the solution is to remove the organization relationship and the permissions should be CRUD for system_admin, read for everyone else. This is aligned with AWX. 

Jira: https://issues.redhat.com/browse/AAP-28076

### CODE REVIEW

**Comment by Alex-Izquierdo** [comment]
E2E tests needs to be updated. It's late for me, I will do it tomorrow and link here the respective successful test run.

**Comment by mkanoor** [comment]
@Alex-Izquierdo A customer can create their own Credential Types, and that could be per Organization, would these Custom Credentials be visible to every Org now with this change.

**Comment by Alex-Izquierdo** [comment]
@mkanoor That's correct. Credential types are understood as system wide content, so each new credential type is visible to every org and only can be created by system admins.

**Review by Dostonbek1 — DISMISSED** [review]
This overall looks good to me, ran it locally and permission class works as expected.

**Comment by hsong-rh** [comment]
@Alex-Izquierdo This change only allows the admin to create credential types, do we need to change documentation to match this?

**Comment by Alex-Izquierdo** [comment]
> @Alex-Izquierdo This change only allows the admin to create credential types, do we need to change documentation to match this?

@hsong-rh that's correct, I'm managing it internally.

**Review by hsong-rh — APPROVED** [review]

**Comment by Alex-Izquierdo** [comment]
succesful E2E test run: https://github.com/ansible/eda-server/actions/runs/10204136436

**Comment by Alex-Izquierdo** [comment]
Please if you can reapprove again @hsong-rh @Dostonbek1 
Just changed the migrations

**Review by hsong-rh — APPROVED** [review]

**Review by hsong-rh — APPROVED** [review]

**Review by Dostonbek1 — APPROVED** [review]

**Pull request merged**
