### PR TITLE
[AAP-19426] Install ansible-vault in  eda-server image

### PR DESCRIPTION
**Pull request by hsong-rh**
Install the package `ansible-core` to the eda image, so the command `ansible-vault` will be available and can be used to encrypt the secrets. 

Tested in its container:
```
[root@af136d926de5 src]# ansible-vault --version
ansible-vault [core 2.14.13]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible-vault
  python version = 3.9.18 (main, Sep  7 2023, 00:00:00) [GCC 11.4.1 20230605 (Red Hat 11.4.1-2)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```
Tested encrypting string:
```
[root@af136d926de5 src]# ansible-vault encrypt_string --vault-password-file password 'foobar' --name 'the_secret'
the_secret: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          37393635663431376138343732663339653863393361643031303834333335353861373831366331
          3662373834353162393933366330363961386161613537340a356538663738666231623038323034
          33343265373566363061613233653637316233333165303838356336623363333266626662666661
          3834633861343565310a653538373633323036363530303833313438316661613466613334323462
          6639Encryption successful
```
Resolves: [AAP-19426](https://issues.redhat.com/browse/AAP-19426)

### CODE REVIEW

**Review by mkanoor — APPROVED** [review]

**Review by ttuffin — APPROVED** [review]

**Comment by Alex-Izquierdo** [comment]
Can you give a bit of context why we need this? Why it is not a dependency of the package?

**Comment by hsong-rh** [comment]
> Can you give a bit of context why we need this? Why it is not a dependency of the package?

@Alex-Izquierdo updated in the description section. Check the ticket link can get more details.

**Comment by Alex-Izquierdo** [comment]
I'm not sure if you are going to use the CLI directly or the library, but I think in both cases this should be a dependency in the project.

**Comment by Alex-Izquierdo** [comment]
Neither I understand why a PR just for a dependency that is not used, I would expect that the PR with the feature would include all the new dependencies.

**Comment by hsong-rh** [comment]
@Alex-Izquierdo `ansible-core` needs python >= 3.10, after changed to it, `podman build image` failed.

**Review by Alex-Izquierdo — CHANGES_REQUESTED** [review]
temporal on hold
This can not be done in main and the dockerfile might not be the right place. Discussing it.

**Comment by hsong-rh** [comment]
Move changes to `devel` branch, closed here

**Pull request closed without merging**
