### PR TITLE
fix: upgrade autobahn to fix issues with setuptools test command

### PR DESCRIPTION
**Pull request by Dostonbek1**
* bump `autobahn` to v24.4.2 directly from github
* bump django-ansible-base to latest devel

### CODE REVIEW

**Review by dhaustein — APPROVED** [review]

**Comment by dhaustein** [comment]
@Dostonbek1 Are we good to lump the DAB upgrade with this?

**Comment by Dostonbek1** [comment]
> @Dostonbek1 Are we good to lump the DAB upgrade with this?

I have not fully tested it yet, just started e2e tests and will manually test it locally as well.

**Review by Alex-Izquierdo — APPROVED** [review]

**Comment by Alex-Izquierdo** [comment]
What is the issue that solves this upgrade?

**Comment by fincamd** [comment]
> What is the issue that solves this upgrade?

@Alex-Izquierdo setuptools removed the test command with this PR https://github.com/pypa/setuptools/pull/4458/, so docker builds were not working

**Review by fincamd — APPROVED** [review]

**Pull request merged**
