### PR TITLE
fix: [AAP-36058] correct the default log_timestamp of RulebookProcessLog records

### PR DESCRIPTION
**Pull request by hsong-rh**
https://issues.redhat.com/browse/AAP-36058

Correct the default value of log_timestamp with the right timestamp.

### CODE REVIEW

**Comment by bzwei** [comment]
@hsong-rh from the example in https://issues.redhat.com/browse/AAP-36058 it shows the messages already have timestamp embedded, can't we extract them and set them in the right column?

**Comment by hsong-rh** [comment]
> @hsong-rh from the example in https://issues.redhat.com/browse/AAP-36058 it shows the messages already have timestamp embedded, can't we extract them and set them in the right column?

Yes, the sample log records have the log_timestamp column, but they were set with the wrong default value of 0. This PR fixes the issue, so all newly generated log records will have the right log_timestamp value. We will leave those existing records untouched because we missed their created timestamps.

**Comment by bzwei** [comment]
> > @hsong-rh from the example in https://issues.redhat.com/browse/AAP-36058 it shows the messages already have timestamp embedded, can't we extract them and set them in the right column?
> 
> Yes, the sample log records have the log_timestamp column, but they were set with the wrong default value of 0. This PR fixes the issue, so all newly generated log records will have the right log_timestamp value. We will leave those existing records untouched because we missed their created timestamps.

I am not requesting to amend existing records. Based on the sample logs if there is already a timestamp in the message body, should we extract it and set it to the right column instead of generating a timestamp based on now()?

**Review by Dostonbek1 — APPROVED** [review]

**Comment by hsong-rh** [comment]
> I am not requesting to amend existing records. Based on the sample logs if there is already a timestamp in the message body, should we extract it and set it to the right column instead of generating a timestamp based on now()?

No, the `log_timestamp` is the only timestamp column in RulebookProcessLog records

**Pull request merged**
