### PR TITLE
[AAP-18826] Integrate Resources API

### PR DESCRIPTION
**Pull request by Dostonbek1**
* implement resource_registry app from django-ansible-base

JIRA: [AAP-18826](https://issues.redhat.com/browse/AAP-18826)

### CODE REVIEW

**Comment by Alex-Izquierdo** [comment]
Don't we need to bump DAB?

**Comment by Dostonbek1** [comment]
> Don't we need to bump DAB?

I initially thought we needed since there was recent migration changes regarding resource_registry lib in dab, but while testing this PR locally I didn't encounter any issues. I will bump it just to be safe.

**Comment by Alex-Izquierdo** [comment]
@Dostonbek1 in your local env you were working with the pinned version? 
I have this:
```
eda-api_1                |   File "/app/venv/lib64/python3.11/site-packages/django/core/management/commands/migrate.py", line 383, in handle
redis_1                  | 1:M 08 Feb 2024 18:35:16.726 * Ready to accept connections
eda-api_1                |     emit_post_migrate_signal(
eda-api_1                |   File "/app/venv/lib64/python3.11/site-packages/django/core/management/sql.py", line 52, in emit_post_migrate_signal
eda-api_1                |     models.signals.post_migrate.send(
eda-api_1                |   File "/app/venv/lib64/python3.11/site-packages/django/dispatch/dispatcher.py", line 176, in send
eda-api_1                |     return [
eda-api_1                |            ^
eda-api_1                |   File "/app/venv/lib64/python3.11/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
eda-api_1                |     (receiver, receiver(signal=self, sender=sender, **named))
eda-api_1                |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
eda-api_1                |   File "/app/venv/lib64/python3.11/site-packages/ansible_base/resource_registry/apps.py", line 60, in initialize_resources
eda-api_1                |     data.append(Resource.init_from_object(obj, resource_type=r_type))
eda-api_1                |                 ^^^^^^^^^^^^^^^^^^^^^^^^^
eda-api_1                | AttributeError: type object 'Resource' has no attribute 'init_from_object'

```

**Comment by Alex-Izquierdo** [comment]
The fact that the tests are green makes me wonder if we need a better test coverage in the integration with DAB

**Comment by Dostonbek1** [comment]
> @Dostonbek1 in your local env you were working with the pinned version? I have this:
> 
> ```
> eda-api_1                |   File "/app/venv/lib64/python3.11/site-packages/django/core/management/commands/migrate.py", line 383, in handle
> redis_1                  | 1:M 08 Feb 2024 18:35:16.726 * Ready to accept connections
> eda-api_1                |     emit_post_migrate_signal(
> eda-api_1                |   File "/app/venv/lib64/python3.11/site-packages/django/core/management/sql.py", line 52, in emit_post_migrate_signal
> eda-api_1                |     models.signals.post_migrate.send(
> eda-api_1                |   File "/app/venv/lib64/python3.11/site-packages/django/dispatch/dispatcher.py", line 176, in send
> eda-api_1                |     return [
> eda-api_1                |            ^
> eda-api_1                |   File "/app/venv/lib64/python3.11/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
> eda-api_1                |     (receiver, receiver(signal=self, sender=sender, **named))
> eda-api_1                |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> eda-api_1                |   File "/app/venv/lib64/python3.11/site-packages/ansible_base/resource_registry/apps.py", line 60, in initialize_resources
> eda-api_1                |     data.append(Resource.init_from_object(obj, resource_type=r_type))
> eda-api_1                |                 ^^^^^^^^^^^^^^^^^^^^^^^^^
> eda-api_1                | AttributeError: type object 'Resource' has no attribute 'init_from_object'
> ```

Yeah this is related with the migrations in resource_registry app, there is a fix for it in DAB but it is after the version that we are using right now. So bumping the DAB version should resolve it.

**Review by Alex-Izquierdo — APPROVED** [review]

**Review by mkanoor — APPROVED** [review]

**Review by jshimkus-rh — APPROVED** [review]

**Pull request merged**
