### PR TITLE
[AAP-14635] Correct worker class name in deployment script

### PR DESCRIPTION
**Pull request by hsong-rh**
This PR contains:
1. added the missing change for worker class name in the deployment script, so OCP worker pod can start;
2. added the missing container `eda-activation-worker`;
3. rename `eda-worker` to `eda-default-worker`

Solves: [AAP-14635](https://issues.redhat.com/browse/AAP-14635)

### CODE REVIEW

**Review by Alex-Izquierdo — DISMISSED** [review]

**Review by Alex-Izquierdo — APPROVED** [review]

**Comment by mkanoor** [comment]
@hsong-rh Don't we need role bindings and service account for the activation-worker? From what I recall those role bindings and service accounts were needed to start activations in k8s env

**Comment by Alex-Izquierdo** [comment]
Good catch! @mkanoor, we need it for new worker.

**Comment by hsong-rh** [comment]
@mkanoor @Alex-Izquierdo Now `activation-worker` has role binding and service accounts, it will handle activation tasks. `default-worker` doesn't need roles and service account.

**Comment by Alex-Izquierdo** [comment]
@hsong-rh I think both workers need it. Deactivate rulesets is executed in the default worker. And we expect that the default worker might do other tasks (scheduled tasks like monitor activations)

**Comment by hsong-rh** [comment]
> @hsong-rh I think both workers need it. Deactivate rulesets is executed in the default worker. And we expect that the default worker might do other tasks (scheduled tasks like monitor activations)

OK, make sense, added them

**Review by Alex-Izquierdo — APPROVED** [review]
LGTM

**Review by Dostonbek1 — APPROVED** [review]
lgtm

**Pull request merged**
