### PR TITLE
feat: add activation-id label for kubernetes resources

### LINKED ISSUE #616: Rulebook restart within kubernetes causes rulebooks to become unavailable
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/aap-eda/issues) for duplicates.
- [X] I understand that EDA-Controller is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Restarting a rulebook activation has two issues:

- if using kubernetes ingress, you must re-deploy the ingress as the service name has changed

- cluster Internal traffic that uses the service name for rulebook access will also loose access to the rulebook as the address has changed, specifically in this case the service name.

### Environment

Kubernetes

### Steps to reproduce

1. start a rulebook activation
2. check service name `kubectl get svc -n <namespace>`
3. note name
4. restart rulebook activation
5. check service name `kubectl get svc -n <namespace>`
6. bam!!! service name different

### Actual results

Service details before restart

``` bash
root@7dd5f0bf32b32b93:/home/deploy# kubectl get svc -n eda
NAME                                                     TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
activation-job-6-16-5003                                 ClusterIP   172.16.41.108   <none>        5003/TCP   6m40s
eda-api                                                  ClusterIP   172.16.41.45    <none>        8000/TCP   3d
eda-daphne                                               ClusterIP   172.16.41.171   <none>        8001/TCP   3d
eda-postgres-13                                          ClusterIP   None            <none>        5432/TCP   3d
eda-redis-svc                                            ClusterIP   172.16.40.199   <none>        6379/TCP   3d
eda-server-operator-controller-manager-metrics-service   ClusterIP   172.16.40.153   <none>        8443/TCP   11d
eda-ui                                                   ClusterIP   172.16.41.34    <none>        80/TCP     3d
root@7dd5f0bf32b32b93:/home/deploy# 
root@7dd5f0bf32b32b93:/home/deploy# 
root@7dd5f0bf32b32b93:/home/deploy# kubectl get svc -n eda activation-job-6-16-5003 -o yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-01-19T18:09:20Z"
  labels:
    app: eda
    job-name: activation-job-6-16
  name: activation-job-6-16-5003
  namespace: eda
  resourceVersion: "5870150"
  uid: 780deb98-8f1a-4f15-b843-2437bfddf2b6
spec:
  clusterIP: 172.16.41.108
  clusterIPs:
  - 172.16.41.108
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 5003
    protocol: TCP
    targetPort: 5003
  selector:
    app: eda
    job-name: activation-job-6-16
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

```

service detais post restart

``` bash

root@7dd5f0bf32b32b93:/home/deploy# kubectl get svc -n eda
NAME                                                     TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
activation-job-6-17-5003                                 ClusterIP   172.16.41.68    <none>        5003/TCP   11s
eda-api                                                  ClusterIP   172.16.41.45    <none>        8000/TCP   3d
eda-daphne                                               ClusterIP   172.16.41.171   <none>        8001/TCP   3d
eda-postgres-13                                          ClusterIP   None            <none>        5432/TCP   3d
eda-redis-svc                                            ClusterIP   172.16.40.199   <none>        6379/TCP   3d
eda-server-operator-controller-manager-metrics-service   ClusterIP   172.16.40.153   <none>        8443/TCP   11d
eda-ui                                                   ClusterIP   172.16.41.34    <none>        80/TCP     3d
root@7dd5f0bf32b32b93:/home/deploy# kubectl get svc -n eda activation-job-6-17-5003 -o yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-01-19T18:39:58Z"
  labels:
    app: eda
    job-name: activation-job-6-17
  name: activation-job-6-17-5003
  namespace: eda
  resourceVersion: "5886550"
  uid: 5acb12fa-6799-406d-8716-b77c8b7b1c37
spec:
  clusterIP: 172.16.41.68
  clusterIPs:
  - 172.16.41.68
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 5003
    protocol: TCP
    targetPort: 5003
  selector:
    app: eda
    job-name: activation-job-6-17
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
root@7dd5f0bf32b32b93:/home/deploy# 

```

### Expected results

That the service name used for the rulebook activation remains the same.  In addition that there also be service labels that remain the same for the service per rulebook so that kubernetes label selectors work.

### Additional information

service name appears to use format   `activation-job-<job-id>-<activation number>-<port>`  i.e.  `activation-job-6-16-5003` dropping the information that is not relevant `<activation number>` and `<port>` would fix 99% of the crux of this issue. This useless "service name" information is better suited to an annotation.

### PR DESCRIPTION
**Pull request by kurokobo**
Closes #616

In the current implementation, the name and label for Job/Pod/Service changes with each restart of the Rulebook Activation. This is a behavior that compromises stability when exposing the Service to the outside of the cluster.

This PR adds the Activation ID as an immutable label that does not change upon restart. This allows users to create arbitrarily named Service with this label as the `selector`, and arbitrarily named Ingress that use it.

There are no side effects because this do not remove nor replace existing labels, but simply add to them.

Changes:

- Add new label `activation-id` to Job, Pod, Service, Secret that created by enabling Rulebook Activation

Tests:

```bash
$ task test -- tests/integration/services/activation/engine/test_kubernetes.py 
task: [test] poetry run python -m pytest tests/integration/services/activation/engine/test_kubernetes.py
====================================== test session starts =======================================
platform linux -- Python 3.9.7, pytest-7.3.1, pluggy-1.0.0
django: settings: aap_eda.settings.development (from env)
rootdir: /home/kuro/work/kurokobo/eda-server
configfile: pytest.ini
plugins: django-4.5.2, asyncio-0.21.0, cov-4.1.0, lazy-fixture-0.6.3, redis-3.0.2
asyncio: mode=auto
collected 27 items                                                                               

tests/integration/services/activation/engine/test_kubernetes.py .......................... [ 96%]
.                                                                                          [100%]

======================================= 27 passed in 2.29s =======================================
```

By enabling Rulebook Activation (ID: 5) that listens inbound connection on 5000, following resources are created:

```
$ kubectl -n eda get job,pod,svc,secret
NAME                            COMPLETIONS   DURATION   AGE
job.batch/activation-job-5-39   0/1           96s        96s

NAME                                                          READY   STATUS    RESTARTS       AGE
...
pod/activation-job-5-39-5fktt                                 1/1     Running   0              96s

NAME                                                             TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
...
service/activation-job-5-39-5000                                 ClusterIP   10.43.34.31     <none>        5000/TCP   94s

NAME                                     TYPE                             DATA   AGE
...
secret/activation-secret-5               kubernetes.io/dockerconfigjson   1      96s


$ kubectl -n eda get job.batch/activation-job-5-39 pod/activation-job-5-39-5fktt service/activation-job-5-39-5000 secret/activation-secret-5 -o yaml
...
- apiVersion: batch/v1
  kind: Job
  metadata:
    ...
    labels:
      activation-id: "5" ✅
      app: eda
      job-name: activation-job-5-39
    name: activation-job-5-39
    namespace: eda
    ...
- apiVersion: v1
  kind: Pod
  metadata:
    ...
    labels:
      activation-id: "5" ✅
      app: eda
      batch.kubernetes.io/controller-uid: 2aaa6f9f-95b8-4aca-a782-cc7bdf33c86c
      batch.kubernetes.io/job-name: activation-job-5-39
      controller-uid: 2aaa6f9f-95b8-4aca-a782-cc7bdf33c86c
      job-name: activation-job-5-39
    name: activation-job-5-39-5fktt
    namespace: eda
    ...
- apiVersion: v1
  kind: Service
  metadata:
    ...
    labels:
      activation-id: "5" ✅
      app: eda
      job-name: activation-job-5-39
    name: activation-job-5-39-5000
    namespace: eda
    ...
- apiVersion: v1
  ...
  kind: Secret
  metadata:
    ...
    labels:
      aap: eda
      activation-id: "5" ✅
    name: activation-secret-5
    namespace: eda
    ...
```

By creating the following Service and Inrgess that refer to this new label, we will not need to modify them after the Rulebook Activation is restarted.

```yaml
---
apiVersion: v1
kind: Service
metadata:
  namespace: eda
  name: webhook-demo-svc ✅
spec:
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector: ✅
    activation-id: "5" ✅
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: eda
  name: webhook-demo-ingress
spec:
  rules:
    - host: webhook-demo.example.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: webhook-demo-svc ✅
                port:
                  number: 5000
```

### CODE REVIEW

**Comment by jon-nfc** [comment]
@kurokobo, your a legend this PR will enable moving forward with implementing!!!

**Comment by kurokobo** [comment]
rebased

**Comment by jon-nfc** [comment]
@Alex-Izquierdo any chance of having this reviewed and merged?

**Comment by Alex-Izquierdo** [comment]
Hi. @kurokobo Thank you very much for your contribution. 

I am not against it, but I need to discuss it with the team first and how we integrate this with our current plans. We are really aware of this problem. This change would also have a very short life as it would be changed soon due to the new features we are working on, the container engine needs to be agnostic of the rulebook type (there will be a new job type in addition to activation).

**Comment by jon-nfc** [comment]
> Hi. @kurokobo Thank you very much for your contribution.
> 
> I am not against it, but I need to discuss it with the team first and how we integrate this with our current plans. We are really aware of this problem. This change would also have a very short life as it would be changed soon due to the new features we are working on, the container engine needs to be agnostic of the rulebook type (there will be a new job type in addition to activation).

@Alex-Izquierdo, thanks for your time for progressing this  PR. Same same for @kurokobo for your work too. May you legends have a cold pillow when you try to sleep tonight!!!

Although the changes in this PR would make EDA a viable solution within the kubernetes environment, are the new features "coming soon (timeframe?)" going to take into account that a service name for instance must remain the same for the life-cycle of the pod? this includes having permanent labels that don't change? as without connectivity will be lost as it is now.

**Comment by Alex-Izquierdo** [comment]
Hi @jon-nfc thanks for your nice words
I can not promise a timeframe; it is a work in progress. We hope to have it completed in the next few weeks. As I mentioned, we are fully aware of this issue, and it is our intention to resolve it. We are evaluating options, one of which is to implement a new field that allows users to set a custom name for the resources. This approach of adding a new label is still valid even without that new field, although there will be more types in addition to activation and the current logic needs to be modified. 

I understand that the current behavior is problematic, but there is no other option than to wait a while for a final solution that fits in with the upcoming features.

@mkanoor @hsong-rh I think adding a new label like "<parent_type>_<parent_id>" is something feasible, thoughts?

**Comment by kurokobo** [comment]
@Alex-Izquierdo 
Thanks for the technical details, I eagerly await the release of the new features.

That said, other high-priority tasks (troubleshooting, incident response, etc.) often make the 'ready soon' schedule not ready at all, so if it's going to take months against your plan, please use this PR as a short-term solution.

I wish you the best of luck with the development of the new feature 😃

**Comment by Alex-Izquierdo** [comment]
Closed in favor of https://github.com/ansible/eda-server/pull/704

**Pull request closed without merging**
