### PR TITLE
[AAP-7174] Database defined default user roles

### PR DESCRIPTION
**Pull request by cutwater**
Drop configuration parameter `EDA_DEFAULT_USER_ROLE` in favor of database defined default user roles.
The `roles` database tables now has new `is_default` field. When `is_default` set to `True`, a role is automatically assigned to a user at user creation or registration.

Implements: https://issues.redhat.com/browse/AAP-7174

## Testing instructions

1. Create an empty database

2. Execute:
    ```
    python scripts/load_data.py tools/initial_data.yml
    ```

3. Login as root:
    ```
    TOKEN=$(http -f POST http://localhost:9000/api/auth/bearer/login username=root@example.com password=secret | jq -r .access_token)
    ```

3. Check roles, a new `is_default` field must be included in response.

    ```
    http -A bearer -a "$TOKEN" http://localhost:9000/api/roles
    [
        {
            "description": "Has full access to all resources",
            "id": "4ca9cd32-e11e-4634-875e-4acf7a5682e1",
            "is_default": false,
            "name": "admin"
        },
        ...
    ```

4. Check your roles, you should see default role in the list of roles.
    ````
    http -A bearer -a "$TOKEN" http://localhost:9000/api/users/me/roles
    [
        {
            "description": "Default role, that is applied to all users",
            "id": "12e9b549-e1eb-40cb-b84b-f289614439af",
            "is_default": true,
            "name": "default"
        }
    ]
    ````

5. Login as any other user, repeat steps 3 and 4.

### CODE REVIEW

**Review by shannon-donahue — DISMISSED** [review]
LGTM

**Review by Alex-Izquierdo — APPROVED** [review]
Verified

**Review by abaiken — APPROVED** [review]
LGTM 👍

**Comment by Dostonbek1** [comment]
@cutwater Just a small comment on this; I believe the PR description shouldn't go as part of commit message, especially if the description is too large. Before merging PRs, we could edit and shorten the description into a brief summary.

**Comment by Alex-Izquierdo** [comment]
@Dostonbek1 @cutwater I Agree. This is configured at repo level. It can be just the title, or the commit message. We can discuss it the next sync meeting

**Comment by cutwater** [comment]
@Dostonbek1 Thank you for this remainder. I forgot to remove the testing instructions from the commit message.

**Pull request merged**
